# Generated by Django 4.0.3 on 2024-10-24 01:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='content',
            field=models.TextField(default='기본내용'),
        ),
        migrations.AddField(
            model_name='answer',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
